# -*- coding: utf-8 -*-
"""new_eda_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npI5ZYrkm7_s9fgYWdPR6HdhAuzQGm9f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import re
import warnings
warnings.filterwarnings('ignore')

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (20, 14)
print("\n" + "="*70)
print("BLOCK 1: LOADING AND PREPARING DATA")
print("="*70)

true_df = pd.read_csv('True.csv', engine='python', on_bad_lines='skip')
fake_df = pd.read_csv('Fake.csv', engine='python', on_bad_lines='skip')

print(f"True dataset loaded: {true_df.shape}")
print(f"Fake dataset loaded: {fake_df.shape}")

# Adding label column
true_df['label'] = 1
fake_df['label'] = 0

# Combining datasets
df = pd.concat([true_df, fake_df], ignore_index=True)

# Removeing subject column
df = df.drop('subject', axis=1)

print(f"Combined dataset shape: {df.shape}")
print(f"Subject column removed")
print(f"\nDataset columns: {list(df.columns)}")

#
#BASIC DATA OVERVIEW
print("\n" + "="*70)
print("BLOCK 2: BASIC DATA OVERVIEW")
print("="*70)

print(f"\nCombined Dataset Shape: {df.shape}")
print(f"True News Count: {len(true_df)} ({len(true_df)/len(df)*100:.1f}%)的发展")
print(f"Fake News Count: {len(fake_df)} ({len(fake_df)/len(df)*100:.1f}%)的")
print(f"\nClass Distribution:")
print(df['label'].value_counts().sort_index().to_string())

# Visualization 1: Class Distribution
fig, ax = plt.subplots(1, 1, figsize=(8, 6))
counts = df['label'].value_counts().sort_index()
colors = ['#FF6B6B', '#4ECDC4']
bars = ax.bar(['Fake News', 'True News'], counts.values, color=colors, edgecolor='black', linewidth=2, width=0.6)
ax.set_ylabel('Number of Articles', fontsize=12, fontweight='bold')
ax.set_title('Class Distribution: True vs Fake News', fontsize=14, fontweight='bold')
ax.set_ylim(0, max(counts.values) * 1.1)
for i, bar in enumerate(bars):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height,
            f'{int(height)}\n({height/len(df)*100:.1f}%)',
            ha='center', va='bottom', fontsize=11, fontweight='bold')
plt.tight_layout()
plt.savefig('01_class_distribution.png', dpi=300, bbox_inches='tight')
print("\nVisualization saved: 01_class_distribution.png")
plt.show
print("\n" + "="*70)
print("BLOCK 3: DATA INFO AND MISSING VALUES")
print("="*70)

print("\nData Info:")
print(df.info())

print("\n\nMissing Values:")
missing = df.isnull().sum()
print(missing.to_string())
print(f"\nTotal missing values: {missing.sum()}")

# Visualization 2: Missing Values Heatmap
fig, ax = plt.subplots(1, 1, figsize=(10, 4))
missing_df = df.isnull().sum().to_frame('Missing')
missing_df['Percentage'] = (missing_df['Missing'] / len(df)) * 100
colors_heatmap = ['#FF6B6B' if x > 0 else '#4ECDC4' for x in missing_df['Missing']]
bars = ax.barh(missing_df.index, missing_df['Percentage'], color=colors_heatmap, edgecolor='black', linewidth=1.5)
ax.set_xlabel('Percentage Missing (%)', fontsize=12, fontweight='bold')
ax.set_title('Missing Values Analysis', fontsize=14, fontweight='bold')
for i, bar in enumerate(bars):
    width = bar.get_width()
    ax.text(width, bar.get_y() + bar.get_height()/2.,
            f'{width:.2f}%',
            ha='left', va='center', fontsize=10, fontweight='bold')
plt.tight_layout()
plt.savefig('02_missing_values.png', dpi=300, bbox_inches='tight')
print("Visualization saved: 02_missing_values.png")
plt.show()

#TEXT LENGTH ANALYSIS
print("\n" + "="*70)
print("BLOCK 4: TEXT LENGTH ANALYSIS")
print("="*70)

df['title_length'] = df['title'].str.len()
df['title_words'] = df['title'].str.split().str.len()
df['text_length'] = df['text'].str.len()
df['text_words'] = df['text'].str.split().str.len()

print("\nTitle Length Statistics:")
print(f"  - Mean title length: {df['title_length'].mean():.2f} characters")
print(f"  - Mean title words: {df['title_words'].mean():.2f}")
print(f"  - Median title words: {df['title_words'].median():.0f}")

print("\nText Length Statistics:")
print(f"  - Mean text length: {df['text_length'].mean():.2f} characters")
print(f"  - Mean text words: {df['text_words'].mean():.2f}")
print(f"  - Median text words: {df['text_words'].median():.0f}")

# Visualization 3: Text Length Comparison
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Title Length Distribution
axes[0, 0].hist(df[df['label']==0]['title_length'], bins=50, alpha=0.7, label='Fake', color='#FF6B6B', edgecolor='black')
axes[0, 0].hist(df[df['label']==1]['title_length'], bins=50, alpha=0.7, label='True', color='#4ECDC4', edgecolor='black')
axes[0, 0].set_xlabel('Title Length (Characters)', fontsize=11, fontweight='bold')
axes[0, 0].set_ylabel('Frequency', fontsize=11, fontweight='bold')
axes[0, 0].set_title('Title Length Distribution', fontsize=12, fontweight='bold')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# Title Words Distribution
axes[0, 1].hist(df[df['label']==0]['title_words'], bins=50, alpha=0.7, label='Fake', color='#FF6B6B', edgecolor='black')
axes[0, 1].hist(df[df['label']==1]['title_words'], bins=50, alpha=0.7, label='True', color='#4ECDC4', edgecolor='black')
axes[0, 1].set_xlabel('Title Words', fontsize=11, fontweight='bold')
axes[0, 1].set_ylabel('Frequency', fontsize=11, fontweight='bold')
axes[0, 1].set_title('Title Word Count Distribution', fontsize=12, fontweight='bold')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# Text Length Distribution
axes[1, 0].hist(df[df['label']==0]['text_length'], bins=50, alpha=0.7, label='Fake', color='#FF6B6B', edgecolor='black')
axes[1, 0].hist(df[df['label']==1]['text_length'], bins=50, alpha=0.7, label='True', color='#4ECDC4', edgecolor='black')
axes[1, 0].set_xlabel('Text Length (Characters)', fontsize=11, fontweight='bold')
axes[1, 0].set_ylabel('Frequency', fontsize=11, fontweight='bold')
axes[1, 0].set_title('Text Length Distribution', fontsize=12, fontweight='bold')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)

# Text Words Distribution
axes[1, 1].hist(df[df['label']==0]['text_words'], bins=50, alpha=0.7, label='Fake', color='#FF6B6B', edgecolor='black')
axes[1, 1].hist(df[df['label']==1]['text_words'], bins=50, alpha=0.7, label='True', color='#4ECDC4', edgecolor='black')
axes[1, 1].set_xlabel('Text Words', fontsize=11, fontweight='bold')
axes[1, 1].set_ylabel('Frequency', fontsize=11, fontweight='bold')
axes[1, 1].set_title('Text Word Count Distribution', fontsize=12, fontweight='bold')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.suptitle('Text Length Analysis: Distribution Comparison', fontsize=14, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('03_text_length_distribution.png', dpi=300, bbox_inches='tight')
print("Visualization saved: 03_text_length_distribution.png")
plt.show()

#BOX PLOT COMPARISON
print("\n" + "="*70)
print("BLOCK 5: BOX PLOT COMPARISON")
print("="*70)

comparison_features = ['title_length', 'title_words', 'text_length', 'text_words']
comparison = df.groupby('label')[comparison_features].mean()
comparison.index = ['Fake', 'True']

print("\nMean Values Comparison:")
print(comparison.to_string())

# Visualization 4: Box Plot Comparison
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

data_to_plot = [
    [df[df['label']==0]['title_length'], df[df['label']==1]['title_length']],
    [df[df['label']==0]['title_words'], df[df['label']==1]['title_words']],
    [df[df['label']==0]['text_length'], df[df['label']==1]['text_length']],
    [df[df['label']==0]['text_words'], df[df['label']==1]['text_words']]
]

titles = ['Title Length (Characters)', 'Title Words', 'Text Length (Characters)', 'Text Words']
ylabels = ['Characters', 'Words', 'Characters', 'Words']

for idx, ax in enumerate(axes.flat):
    bp = ax.boxplot(data_to_plot[idx], labels=['Fake', 'True'], patch_artist=True,
                     medianprops=dict(color='red', linewidth=2),
                     boxprops=dict(facecolor='lightblue', alpha=0.7),
                     whiskerprops=dict(linewidth=1.5),
                     capprops=dict(linewidth=1.5))

    # Color boxes
    colors = ['#FF6B6B', '#4ECDC4']
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)

    ax.set_ylabel(ylabels[idx], fontsize=11, fontweight='bold')
    ax.set_title(titles[idx], fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3, axis='y')

plt.suptitle('Box Plot Comparison: True vs Fake News', fontsize=14, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('04_box_plot_comparison.png', dpi=300, bbox_inches='tight')
print("Visualization saved: 04_box_plot_comparison.png")
plt.show()

#STATISTICAL SUMMARY VISUALIZATION

print("\n" + "="*70)
print("BLOCK 6: STATISTICAL SUMMARY")
print("="*70)

print("\nStatistical Summary for Length Features:")
length_stats = df[['title_length', 'title_words', 'text_length', 'text_words']].describe()
print(length_stats.to_string())

#Statistical Comparison Bar Chart
fig, ax = plt.subplots(1, 1, figsize=(14, 6))

x_labels = ['Title Length', 'Title Words', 'Text Length', 'Text Words']
fake_means = [df[df['label']==0][feat].mean() for feat in comparison_features]
true_means = [df[df['label']==1][feat].mean() for feat in comparison_features]

x = np.arange(len(x_labels))
width = 0.35

bars1 = ax.bar(x - width/2, fake_means, width, label='Fake News', color='#FF6B6B', edgecolor='black', linewidth=1.5)
bars2 = ax.bar(x + width/2, true_means, width, label='True News', color='#4ECDC4', edgecolor='black', linewidth=1.5)

ax.set_ylabel('Mean Value', fontsize=12, fontweight='bold')
ax.set_title('Mean Comparison: True vs Fake News', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(x_labels)
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3, axis='y')

# Add value labels on bars
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.0f}',
                ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('05_statistical_comparison.png', dpi=300, bbox_inches='tight')
print("Visualization saved: 05_statistical_comparison.png")
plt.show()

#
#TEMPORAL ANALYSIS
print("\n" + "="*70)
print("BLOCK 7: TEMPORAL ANALYSIS")
print("="*70)

df['date'] = pd.to_datetime(df['date'], format='%B %d, %Y', errors='coerce')
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

print(f"\nDate Range:")
print(f"  - Start Date: {df['date'].min()}")
print(f"  - End Date: {df['date'].max()}")
print(f"  - Time Span: {(df['date'].max() - df['date'].min()).days} days")

print(f"\nArticles per Year:")
print(df['year'].value_counts().sort_index().to_string())

#Temporal Distribution
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Articles per Year
yearly_counts = df['year'].value_counts().sort_index()
axes[0].bar(yearly_counts.index, yearly_counts.values, color='#95E1D3', edgecolor='black', linewidth=1.5, width=0.6)
axes[0].set_xlabel('Year', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Number of Articles', fontsize=12, fontweight='bold')
axes[0].set_title('Articles Published Per Year', fontsize=13, fontweight='bold')
axes[0].grid(True, alpha=0.3, axis='y')
for i, v in enumerate(yearly_counts.values):
    axes[0].text(yearly_counts.index[i], v, str(int(v)), ha='center', va='bottom', fontweight='bold')

# True vs Fake per Year
year_label = df.groupby(['year', 'label']).size().unstack(fill_value=0)
year_label.plot(kind='bar', ax=axes[1], color=['#FF6B6B', '#4ECDC4'], edgecolor='black', linewidth=1.5)
axes[1].set_xlabel('Year', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Number of Articles', fontsize=12, fontweight='bold')
axes[1].set_title('True vs Fake Articles Per Year', fontsize=13, fontweight='bold')
axes[1].legend(['Fake', 'True'], fontsize=11)
axes[1].grid(True, alpha=0.3, axis='y')
axes[1].set_xticklabels(year_label.index, rotation=45)

plt.tight_layout()
plt.savefig('06_temporal_analysis.png', dpi=300, bbox_inches='tight')
print("Visualization saved: 06_temporal_analysis.png")
plt.show()

#TEXT CHARACTERISTICS
print("\n" + "="*70)
print("BLOCK 8: TEXT CHARACTERISTICS")
print("="*70)

# Punctuation counts
df['exclamation_count'] = df['text'].apply(lambda x: str(x).count('!'))
df['question_count'] = df['text'].apply(lambda x: str(x).count('?'))
df['quote_count'] = df['text'].apply(lambda x: str(x).count('"'))

punct_comp = df.groupby('label')[['exclamation_count', 'question_count', 'quote_count']].mean()
punct_comp.index = ['Fake', 'True']

print("\nPunctuation Statistics (True vs Fake):")
print(punct_comp.to_string())

# URLs
df['url_count'] = df['text'].apply(lambda x: len(re.findall(r'http[s]?://\S+', str(x))))
df['has_urls'] = (df['url_count'] > 0).astype(int)

print(f"\nURL Statistics:")
print(f"  - Avg URLs per article (Fake): {df[df['label']==0]['url_count'].mean():.2f}")
print(f"  - Avg URLs per article (True): {df[df['label']==1]['url_count'].mean():.2f}")

# Numbers
df['number_count'] = df['text'].apply(lambda x: len(re.findall(r'\d+', str(x))))

print(f"\nNumber Statistics:")
print(f"  - Avg numbers per article (Fake): {df[df['label']==0]['number_count'].mean():.2f}")
print(f"  - Avg numbers per article (True): {df[df['label']==1]['number_count'].mean():.2f}")

#Text Characteristics
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Exclamation Marks
exc_fake = df[df['label']==0]['exclamation_count'].mean()
exc_true = df[df['label']==1]['exclamation_count'].mean()
axes[0, 0].bar(['Fake', 'True'], [exc_fake, exc_true], color=['#FF6B6B', '#4ECDC4'], edgecolor='black', linewidth=1.5, width=0.5)
axes[0, 0].set_ylabel('Average Count', fontsize=11, fontweight='bold')
axes[0, 0].set_title('Exclamation Marks', fontsize=12, fontweight='bold')
axes[0, 0].grid(True, alpha=0.3, axis='y')
for i, v in enumerate([exc_fake, exc_true]):
    axes[0, 0].text(i, v, f'{v:.2f}', ha='center', va='bottom', fontweight='bold')

# Question Marks
que_fake = df[df['label']==0]['question_count'].mean()
que_true = df[df['label']==1]['question_count'].mean()
axes[0, 1].bar(['Fake', 'True'], [que_fake, que_true], color=['#FF6B6B', '#4ECDC4'], edgecolor='black', linewidth=1.5, width=0.5)
axes[0, 1].set_ylabel('Average Count', fontsize=11, fontweight='bold')
axes[0, 1].set_title('Question Marks', fontsize=12, fontweight='bold')
axes[0, 1].grid(True, alpha=0.3, axis='y')
for i, v in enumerate([que_fake, que_true]):
    axes[0, 1].text(i, v, f'{v:.2f}', ha='center', va='bottom', fontweight='bold')

# URLs
url_fake = df[df['label']==0]['url_count'].mean()
url_true = df[df['label']==1]['url_count'].mean()
axes[1, 0].bar(['Fake', 'True'], [url_fake, url_true], color=['#FF6B6B', '#4ECDC4'], edgecolor='black', linewidth=1.5, width=0.5)
axes[1, 0].set_ylabel('Average Count', fontsize=11, fontweight='bold')
axes[1, 0].set_title('URLs in Text', fontsize=12, fontweight='bold')
axes[1, 0].grid(True, alpha=0.3, axis='y')
for i, v in enumerate([url_fake, url_true]):
    axes[1, 0].text(i, v, f'{v:.2f}', ha='center', va='bottom', fontweight='bold')

# Numbers
num_fake = df[df['label']==0]['number_count'].mean()
num_true = df[df['label']==1]['number_count'].mean()
axes[1, 1].bar(['Fake', 'True'], [num_fake, num_true], color=['#FF6B6B', '#4ECDC4'], edgecolor='black', linewidth=1.5, width=0.5)
axes[1, 1].set_ylabel('Average Count', fontsize=11, fontweight='bold')
axes[1, 1].set_title('Numbers in Text', fontsize=12, fontweight='bold')
axes[1, 1].grid(True, alpha=0.3, axis='y')
for i, v in enumerate([num_fake, num_true]):
    axes[1, 1].text(i, v, f'{v:.2f}', ha='center', va='bottom', fontweight='bold')

plt.suptitle('Text Characteristics Comparison', fontsize=14, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('07_text_characteristics.png', dpi=300, bbox_inches='tight')
print("Visualization saved: 07_text_characteristics.png")
plt.show()

#CORRELATION HEATMAP
print("\n" + "="*70)
print("BLOCK 10: CORRELATION ANALYSIS")
print("="*70)

correlation_features = ['title_length', 'title_words', 'text_length', 'text_words',
                        'exclamation_count', 'question_count', 'url_count', 'number_count', 'label']
corr_matrix = df[correlation_features].corr()

print("\nCorrelation with Label:")
print(corr_matrix['label'].sort_values(ascending=False).to_string())

# Visualization : Correlation Heatmap
fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='RdBu_r', center=0,
            square=True, linewidths=1, cbar_kws={"shrink": 0.8}, ax=ax)
ax.set_title('Correlation Matrix Heatmap', fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('09_correlation_heatmap.png', dpi=300, bbox_inches='tight')
print("Visualization saved: 09_correlation_heatmap.png")
plt.show()

#SAVE PROCESSED DATA
print("\n" + "="*70)
print("BLOCK 11: SAVING PROCESSED DATA")
print("="*70)

df_processed = df[['title', 'text', 'date', 'label']].copy()
df_processed.to_csv('processed_data.csv', index=False)
print("Processed dataset saved as 'processed_data.csv'")
print(f"  - Shape: {df_processed.shape}")

#FINAL SUMMARY
print("\n" + "="*70)
print("BLOCK 12: FINAL SUMMARY")
print("="*70)

print(f"\nANALYSIS COMPLETE!")
print(f"\nVisualizations Generated (9 files):")
print(f"  - 01_class_distribution.png")
print(f"  - 02_missing_values.png")
print(f"  - 03_text_length_distribution.png")
print(f"  - 04_box_plot_comparison.png")
print(f"  - 05_statistical_comparison.png")
print(f"  - 06_temporal_analysis.png")
print(f"  - 07_text_characteristics.png")
print(f"  - 08_violin_plots.png")
print(f"  - 09_correlation_heatmap.png")

print(f"\nDataset Summary:")
print(f"  - Total articles: {len(df)}")
print(f"  - True articles: {len(true_df)} ({len(true_df)/len(df)*100:.1f}%)")
print(f"  - Fake articles: {len(fake_df)} ({len(fake_df)/len(df)*100:.1f}%)")
print(f"  - Date range: {df['date'].min().date()} to {df['date'].max().date()}")

print(f"\nKey Findings:")
print(f"  - Avg title length (Fake): {df[df['label']==0]['title_length'].mean():.0f} chars")
print(f"  - Avg title length (True): {df[df['label']==1]['title_length'].mean():.0f} chars")
print(f"  - Avg text length (Fake): {df[df['label']==0]['text_length'].mean():.0f} chars")
print(f"  - Avg text length (True): {df[df['label']==1]['text_length'].mean():.0f} chars")
print(f"  - Avg exclamations (Fake): {df[df['label']==0]['exclamation_count'].mean():.2f}")
print(f"  - Avg exclamations (True): {df[df['label']==1]['exclamation_count'].mean():.2f}")

print(f"\nReady for Model Building!")
print("="*70)